spring:
  profiles:
    active: default
---
spring:
  config:
    activate:
      on-profile: default
---
spring:
  h2:
    console:
      enabled: true
---

spring:
  devtools:
    add-properties: false

---

server:
  port: 9191
  
---
spring:
  datasource:
    url: jdbc:h2:mem:testdb
